### ISSUE TITLE
Encoding Problem Python3

### ISSUE THREAD

**Issue by NicoDietrich** [blatinier/pyhunspell#32] opened 2017-07-21 14:30 UTC
Hey! I have a problem using hunspell with german words and I hope you can help me out.
An Example:

```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hunspell
>>> spellchecker = hunspell.HunSpell('/usr/share/hunspell/de_DE.dic',
...                                  '/usr/share/hunspell/de_DE.aff')
>>> spellchecker.spell('Wörterbuch')
True
>>> spellchecker.suggest('Wörterbuhc')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method suggest of HunSpell object at 0xb717d6d0> returned a result with an error set
```

When I encode to utf-8 it works, but the result I get makes no sense:

```python
>>> spellchecker.suggest('Wörterbuhc'.encode('utf-8'))
['Westerburger']
```
This seems to be very weird, since [here](https://datascience.blog.wzb.eu/2016/07/13/autocorrecting-misspelled-words-in-python-using-hunspell/) was done the exact same thing which apparently worked.

I use it in a Ubuntu VM with all the necessary packages installed:
>Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04

**Comment by blatinier** [comment] 2017-07-22 21:29
Ok I can reproduce something similar. But not exactly. Here is what I have:
```
>>> import hunspell
>>> spellchecker = hunspell.HunSpell('/usr/share/hunspell/de_DE.dic','/usr/share/hunspell/de_DE.aff')
>>> spellchecker.spell('Wörterbuch')
True
>>> spellchecker.suggest('Wörterbuhc') # should return some result, not an empty list
[]
>>> spellchecker.suggest('Wörterbuhc'.encode('utf-8')) # should not fail
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 1: invalid start byte
```
I will inquire on this later a bit later.

Can you attach your ubuntu version for the record please?

**Comment by PanderMusubi** [comment] 2017-07-23 09:49
In my applications, i use

`if filename in ('de_AT_frami.aff', 'de_CH_frami.aff', 'de_DE_frami.aff', 'de_DE.aff', 'en_US.aff', 'pt_BR.aff', 'sl_SI.aff', 'th_TH.aff', 'ru_RU.aff', 'nn_NO.aff', 'an_ES.aff', 'af_ZA.aff', 'el_GR.aff', 'bg_
BG.aff', 'de_CH.aff', 'it_IT.aff', 'hu_HU.aff', 'pl_PL.aff', 'cs_CZ.aff', 'eu.aff', 'lt_LT.aff', 'nb_NO.aff', 'oc_FR.aff', 'bs_BA.aff', 'de_AT.aff', ):`
`    input = open(filepath, 'r', encoding='ISO-8859-1')`
`else:`
`    input = open(filepath, 'r')`

**Comment by mike-fabian** [comment] 2017-09-04 08:49
I see a similar problem on Fedora 26:

$ python3
Python 3.6.2 (default, Aug 11 2017, 11:59:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hunspell
>>> hobj = hunspell.HunSpell('/usr/share/myspell/de_DE.dic', '/usr/share/myspell/de_DE.aff')
>>> hobj.suggest('grun')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method suggest of HunSpell object at 0x7f32edc26a50> returned a result with an error set
>>> 


I think “grün” should be among the suggestions, but it fails because of the encoding error.

**Comment by isnok** [comment] 2017-09-04 13:04
+1
I just ran into similar trouble with the german word "Gültigkeit".
Thanks to this thread I found that it is actually valid (hobj.spell returns True), but hobj.suggest raises the same UnicodeDecodeError... (can't decode at position 1)

**Comment by isnok** [comment] 2017-09-04 13:07
Update: I tried with `hunspell==0.4.0` and it works!

**Comment by rafis** [comment] 2018-02-05 13:42
The problem still exists even for pure ASCII words:

```python
import hunspell
hobj = hunspell.HunSpell('/usr/share/hunspell/en_US.dic', '/usr/share/hunspell/en_US.aff')
print(hobj.suggest('Eelysa'))
```

**Comment by thierry-FreeBSD** [comment] 2018-02-18 12:29
Same error with 0.5.3. See https://github.com/mike-fabian/ibus-typing-booster/issues/23

**Comment by blatinier** [comment] 2018-02-20 21:51
I think it's ok in master now. If someone confirm I will publish rapidly a new version on pypi

**Comment by blatinier** [comment] 2018-02-20 21:53
For the record, some dic are Latin1 encoded, I try some UTF-8 first and on fail I fallback on Latin1.

**Comment by mike-fabian** [comment] 2018-03-06 08:57
Benoît Latinier <notifications@github.com> さんは書きました:

> For the record, some dic are Latin1 encoded, I try some UTF-8 first and on fail I fallback on Latin1.

The problem seems to be fixed in current git master indeed.

-- 
📧 Mike FABIAN   <mike.fabian@gmx.de>
睡眠不足はいい仕事の敵だ。

**Comment by nkrot** [comment] 2018-03-06 11:45
in hunspell (0.5.3) still the same problem when using HunSpell.suggest() with German umlauts.?

    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 5: invalid start byte

Any chances to get it fixed or a working workaround?

**Comment by mike-fabian** [comment] 2018-03-06 13:19
@nkrot Current git master worked for me doing this:


$ python3
Python 3.6.4 (default, Feb  8 2018, 14:42:51) 
[GCC 7.3.1 20180130 (Red Hat 7.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hunspell
>>> hobj = hunspell.HunSpell('/usr/share/myspell/de_DE.dic', '/usr/share/myspell/de_DE.aff')
>>> hobj.suggest('grun')
['grub', 'grün', '-run', 'Grund', 'Grunge']
>>>

**Comment by blatinier** [comment] 2018-03-07 14:01
@nkrot since current master solves this encoding issue, I published a new version (0.5.4 → https://pypi.python.org/pypi/hunspell/0.5.4)
You can try it.

**Closed by blatinier** 2018-03-07 14:01 UTC

**Comment by djstrong** [comment] 2019-03-22 18:29
Encoding is wrong:
```
hobj = hunspell.HunSpell('/usr/share/hunspell/pl_PL.dic', '/usr/share/hunspell/pl_PL.aff')
hobj.get_dic_encoding()
'ISO8859-2'
hobj.suggest('narazie')
['zaranie',
 'narazi',
 'narzazie',
 'naradzie',
 'zarazie',
 'nakazie',
 'namazie',
 'nardzie',
 'narazi³',
 'naraziæ',
 'na razie',
 'na-razie',
 'nara zie',
 'nara-zie',
 'naraz ie']
```
Instead of "narazi³" and "naraziæ" should be "narazić" and "naraził".

**Comment by petasis** [comment] 2019-08-14 08:49
I am re-opening this bug, as the solution provided is not a complete fix.
I am using the Greek dictionary, which has an iso-8859-7 encoding.
Using PyUnicode_DecodeLatin1() return invalid results.
